version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./front-end
    ports:
      - 8080:8080
    working_dir: /app-frontend
    volumes:
      - ./front-end/src:/app-frontend/src
    restart: 'always'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:8080']
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build:
      context: ./back-end/back-end.Web
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
      - 3002:3002
    depends_on:
      frontend:
        condition: service_healthy
    restart: 'always'
    environment:
      - DOTNET_CONNECTION_STRING:@"Server=db; Database=students_db; Uid=root; Password=123456;"
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001']
      timeout: 30s
      retries: 15
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 120s
      retries: 40
    cap_add:
      - SYS_NICE